{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"クエリ1\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "ja-JP",
    "cultures": [
      {
        "name": "ja-JP",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "ja-JP",
    "tables": [
      {
        "name": "DateTableTemplate_a689dd76-2e0f-42b4-85b1-cf689f9d679f",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2608efb3-04f8-4827-9c5b-55bc6f9360fc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fd63dcb6-4e9f-4876-98d0-2e0d0d44d179",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "730b8b2c-fb00-4c27-9f3f-b837bb1d942b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e70bade8-4dec-473f-b4e3-b953aa87b706",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "22d6d945-95dd-4840-a21b-31f99c46e475",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "四半期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2d3c8ecf-277a-4a5b-b8ba-47e74b3232e7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7ced63fd-d66c-451e-b08a-756b2cc38504",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日付の階層",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "3c7d4d1f-cbe6-4f98-b5b3-1c467bf09058",
                "ordinal": 0
              },
              {
                "name": "四半期",
                "column": "四半期",
                "lineageTag": "b2fa025b-d7d8-41cd-848f-0cc5bfcbf48d",
                "ordinal": 1
              },
              {
                "name": "月",
                "column": "月",
                "lineageTag": "1fb7b1c4-c624-4291-8278-393c4bfd7808",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "d7854539-9aed-426f-9a23-3173d95c6793",
                "ordinal": 3
              }
            ],
            "lineageTag": "3f9e2620-a43b-4ebd-bf76-86b47e0ab7d9"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f34558f6-1ab1-48c0-ba80-e6ddecb6e0ed",
        "partitions": [
          {
            "name": "DateTableTemplate_a689dd76-2e0f-42b4-85b1-cf689f9d679f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "クエリ1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "ナビゲーション"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1578e93f-e79b-4804-b2ba-9d81e19a046a",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "MSSubClass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c1ed7e7-60ff-4e38-9c60-514c543c860c",
            "sourceColumn": "MSSubClass",
            "summarizeBy": "sum"
          },
          {
            "name": "MSZoning",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c955610d-e976-4688-bf03-c4c9e88c0adf",
            "sourceColumn": "MSZoning",
            "summarizeBy": "none"
          },
          {
            "name": "LotFrontage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f0565e8-2df3-4ab9-9c32-8d9b95f76461",
            "sourceColumn": "LotFrontage",
            "summarizeBy": "sum"
          },
          {
            "name": "LotArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "39d5e69e-0b94-4657-8209-3cbe3c4513c2",
            "sourceColumn": "LotArea",
            "summarizeBy": "sum"
          },
          {
            "name": "Street",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec51fb96-3975-44ee-8ec8-7872c3d56b36",
            "sourceColumn": "Street",
            "summarizeBy": "none"
          },
          {
            "name": "Alley",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0f0911e-8f55-4a80-8669-55fac90d0db2",
            "sourceColumn": "Alley",
            "summarizeBy": "none"
          },
          {
            "name": "LotShape",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62b995f2-20af-438a-b2e4-2c09489ed449",
            "sourceColumn": "LotShape",
            "summarizeBy": "none"
          },
          {
            "name": "LandContour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e426c18d-5f83-42be-837b-6eee6ca37988",
            "sourceColumn": "LandContour",
            "summarizeBy": "none"
          },
          {
            "name": "Utilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79c1d171-2dc6-4e72-aefb-c70976652940",
            "sourceColumn": "Utilities",
            "summarizeBy": "none"
          },
          {
            "name": "LotConfig",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1c5b0d0-00d7-4a1a-8b49-21872954b758",
            "sourceColumn": "LotConfig",
            "summarizeBy": "none"
          },
          {
            "name": "LandSlope",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0e81417-d17a-44ec-87a4-78fcb5d5b54c",
            "sourceColumn": "LandSlope",
            "summarizeBy": "none"
          },
          {
            "name": "Neighborhood",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bac0a21a-7212-4885-8582-f44278654681",
            "sourceColumn": "Neighborhood",
            "summarizeBy": "none"
          },
          {
            "name": "Condition1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a88d7444-bdc6-4129-84ff-d87a44011f56",
            "sourceColumn": "Condition1",
            "summarizeBy": "none"
          },
          {
            "name": "Condition2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b52397a7-9c07-48b8-88c8-ce1fc4ba436e",
            "sourceColumn": "Condition2",
            "summarizeBy": "none"
          },
          {
            "name": "BldgType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae2fa43b-2b32-4daa-be7f-226c54fff483",
            "sourceColumn": "BldgType",
            "summarizeBy": "none"
          },
          {
            "name": "HouseStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ad193be-2f87-4140-b7ee-ed0441aa7893",
            "sourceColumn": "HouseStyle",
            "summarizeBy": "none"
          },
          {
            "name": "OverallQual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "721a9fc0-fc6a-451c-b1e6-6a94b83e2693",
            "sourceColumn": "OverallQual",
            "summarizeBy": "sum"
          },
          {
            "name": "OverallCond",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a4db92c-3b90-4eb9-a8c5-1d67c67bcfb0",
            "sourceColumn": "OverallCond",
            "summarizeBy": "sum"
          },
          {
            "name": "YearBuilt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "62c1a6fe-9ca4-4071-ac6a-111c546cc991",
            "sourceColumn": "YearBuilt",
            "summarizeBy": "sum"
          },
          {
            "name": "YearRemodAdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5fb2db46-ac5e-4fa6-9122-b904e4ec8fde",
            "sourceColumn": "YearRemodAdd",
            "summarizeBy": "sum"
          },
          {
            "name": "RoofStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47017ff0-8142-4812-8f90-8f9383dc5771",
            "sourceColumn": "RoofStyle",
            "summarizeBy": "none"
          },
          {
            "name": "RoofMatl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89d69896-392a-4a03-b779-29c82c49e111",
            "sourceColumn": "RoofMatl",
            "summarizeBy": "none"
          },
          {
            "name": "Exterior1st",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e948ebc-9158-43d7-92fc-e15176cb9d71",
            "sourceColumn": "Exterior1st",
            "summarizeBy": "none"
          },
          {
            "name": "Exterior2nd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59ed1bf1-fea1-4fe1-82ba-bf088baa4e12",
            "sourceColumn": "Exterior2nd",
            "summarizeBy": "none"
          },
          {
            "name": "MasVnrType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "908b9157-a2ac-49c3-a7a8-752181673b86",
            "sourceColumn": "MasVnrType",
            "summarizeBy": "none"
          },
          {
            "name": "MasVnrArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f26d407d-460a-44da-aec0-493d0306d73b",
            "sourceColumn": "MasVnrArea",
            "summarizeBy": "sum"
          },
          {
            "name": "ExterQual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f195630b-9991-4bac-a8a2-c5976a4f0f32",
            "sourceColumn": "ExterQual",
            "summarizeBy": "none"
          },
          {
            "name": "ExterCond",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "859ff95f-ea2d-47ad-a071-22b9ffe552b6",
            "sourceColumn": "ExterCond",
            "summarizeBy": "none"
          },
          {
            "name": "Foundation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5bd9cab-f098-4629-ac0e-c3d0eb6a5549",
            "sourceColumn": "Foundation",
            "summarizeBy": "none"
          },
          {
            "name": "BsmtQual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9db07b1-72a3-4752-a23e-75d77d8b6a9e",
            "sourceColumn": "BsmtQual",
            "summarizeBy": "none"
          },
          {
            "name": "BsmtCond",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a905ecdc-da64-4ea5-bd26-3338890aeaf5",
            "sourceColumn": "BsmtCond",
            "summarizeBy": "none"
          },
          {
            "name": "BsmtExposure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47534687-98ca-4d17-9ccd-fbe2ed8d96fc",
            "sourceColumn": "BsmtExposure",
            "summarizeBy": "none"
          },
          {
            "name": "BsmtFinType1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2d515fa-ac65-4919-b518-bf6117eced23",
            "sourceColumn": "BsmtFinType1",
            "summarizeBy": "none"
          },
          {
            "name": "BsmtFinSF1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3efea7b-d606-4702-8e83-2ac6c107ee81",
            "sourceColumn": "BsmtFinSF1",
            "summarizeBy": "sum"
          },
          {
            "name": "BsmtFinType2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41baa2a4-47c9-4e46-9558-6d7a3d296a25",
            "sourceColumn": "BsmtFinType2",
            "summarizeBy": "none"
          },
          {
            "name": "BsmtFinSF2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cfc39c59-f538-482d-bef9-29ad753c1e04",
            "sourceColumn": "BsmtFinSF2",
            "summarizeBy": "sum"
          },
          {
            "name": "BsmtUnfSF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fa59acb0-eef8-4807-ae9b-1f4d0b7973d8",
            "sourceColumn": "BsmtUnfSF",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalBsmtSF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b06e9fa-558f-41a3-ae05-91942e9fae14",
            "sourceColumn": "TotalBsmtSF",
            "summarizeBy": "sum"
          },
          {
            "name": "Heating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b81f60f0-b9fb-48d0-b7f9-a5954dc1492c",
            "sourceColumn": "Heating",
            "summarizeBy": "none"
          },
          {
            "name": "HeatingQC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a075f973-2381-4ac1-a12a-2b15380bc817",
            "sourceColumn": "HeatingQC",
            "summarizeBy": "none"
          },
          {
            "name": "CentralAir",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e9b86a2-b85d-40b8-8aba-3621a3b3d86a",
            "sourceColumn": "CentralAir",
            "summarizeBy": "none"
          },
          {
            "name": "Electrical",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd565f7a-8b5f-46bf-87a9-bb020c3d468f",
            "sourceColumn": "Electrical",
            "summarizeBy": "none"
          },
          {
            "name": "1stFlrSF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a398b9be-2fd0-413c-9623-9ddfd059a8c6",
            "sourceColumn": "1stFlrSF",
            "summarizeBy": "sum"
          },
          {
            "name": "2ndFlrSF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f9a0f84-34a2-454b-969f-4884718f970d",
            "sourceColumn": "2ndFlrSF",
            "summarizeBy": "sum"
          },
          {
            "name": "LowQualFinSF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "446feb44-aa61-4623-8140-69f1066069b9",
            "sourceColumn": "LowQualFinSF",
            "summarizeBy": "sum"
          },
          {
            "name": "GrLivArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f99da93a-59df-49d0-a9bf-783a7e05c9bc",
            "sourceColumn": "GrLivArea",
            "summarizeBy": "sum"
          },
          {
            "name": "BsmtFullBath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7154b19e-2476-4e20-a2d3-51e23ec5673c",
            "sourceColumn": "BsmtFullBath",
            "summarizeBy": "sum"
          },
          {
            "name": "BsmtHalfBath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cf426956-052b-4bbb-b4cf-759436fd8775",
            "sourceColumn": "BsmtHalfBath",
            "summarizeBy": "sum"
          },
          {
            "name": "FullBath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a39facf9-6ac7-421d-b04c-2795c0cb4df6",
            "sourceColumn": "FullBath",
            "summarizeBy": "sum"
          },
          {
            "name": "HalfBath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41674f04-5b04-4df2-b52c-0d7b565be4da",
            "sourceColumn": "HalfBath",
            "summarizeBy": "sum"
          },
          {
            "name": "BedroomAbvGr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa3a9491-d69a-4d35-b7c8-82cea85d856f",
            "sourceColumn": "BedroomAbvGr",
            "summarizeBy": "sum"
          },
          {
            "name": "KitchenAbvGr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c1a3fe02-9b0a-4eaf-8284-291a7bea24dc",
            "sourceColumn": "KitchenAbvGr",
            "summarizeBy": "sum"
          },
          {
            "name": "KitchenQual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "912f6d4b-1d85-47ea-9ac7-00c784d42d85",
            "sourceColumn": "KitchenQual",
            "summarizeBy": "none"
          },
          {
            "name": "TotRmsAbvGrd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "612cc2aa-9130-484b-9016-cd5fa93e74ad",
            "sourceColumn": "TotRmsAbvGrd",
            "summarizeBy": "sum"
          },
          {
            "name": "Functional",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe5c2e98-17af-440d-9df2-484307598e95",
            "sourceColumn": "Functional",
            "summarizeBy": "none"
          },
          {
            "name": "Fireplaces",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2522bb3-6470-4631-80db-8812f5d5adc0",
            "sourceColumn": "Fireplaces",
            "summarizeBy": "sum"
          },
          {
            "name": "FireplaceQu",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e23f8f2a-80b5-4a79-b923-72752ab4fb2a",
            "sourceColumn": "FireplaceQu",
            "summarizeBy": "none"
          },
          {
            "name": "GarageType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4bdc4f3-9733-442d-86fb-b10fee2f400c",
            "sourceColumn": "GarageType",
            "summarizeBy": "none"
          },
          {
            "name": "GarageYrBlt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cccf4527-e611-4208-ba82-da25495cb249",
            "sourceColumn": "GarageYrBlt",
            "summarizeBy": "sum"
          },
          {
            "name": "GarageFinish",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64a8d7cc-80ac-4478-bc96-b0bff1bcc137",
            "sourceColumn": "GarageFinish",
            "summarizeBy": "none"
          },
          {
            "name": "GarageCars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c848693-82fe-41e5-862a-062b81d3c8cb",
            "sourceColumn": "GarageCars",
            "summarizeBy": "sum"
          },
          {
            "name": "GarageArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2af2198e-d4e1-4123-8d95-b24c4ce23f96",
            "sourceColumn": "GarageArea",
            "summarizeBy": "sum"
          },
          {
            "name": "GarageQual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccc762fd-9df9-417d-aeb5-bbca47017934",
            "sourceColumn": "GarageQual",
            "summarizeBy": "none"
          },
          {
            "name": "GarageCond",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3713295a-02ea-4abc-b5c6-6e0ceb25d5bb",
            "sourceColumn": "GarageCond",
            "summarizeBy": "none"
          },
          {
            "name": "PavedDrive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6f8c15b-d477-4b18-bee9-18b76eafd800",
            "sourceColumn": "PavedDrive",
            "summarizeBy": "none"
          },
          {
            "name": "WoodDeckSF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a9a64065-54ac-4b23-be4d-71c6150445da",
            "sourceColumn": "WoodDeckSF",
            "summarizeBy": "sum"
          },
          {
            "name": "OpenPorchSF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b85f4079-0bbf-4741-b79f-988cd68a825f",
            "sourceColumn": "OpenPorchSF",
            "summarizeBy": "sum"
          },
          {
            "name": "EnclosedPorch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7024075d-522b-42fc-85bb-a0f2b5ccff54",
            "sourceColumn": "EnclosedPorch",
            "summarizeBy": "sum"
          },
          {
            "name": "3SsnPorch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7db3bb7-f067-4c44-9ade-482de064ceac",
            "sourceColumn": "3SsnPorch",
            "summarizeBy": "sum"
          },
          {
            "name": "ScreenPorch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88f51289-3ade-4a43-a413-40b5c308347a",
            "sourceColumn": "ScreenPorch",
            "summarizeBy": "sum"
          },
          {
            "name": "PoolArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a129af90-583b-4d6e-9ede-12e7024da975",
            "sourceColumn": "PoolArea",
            "summarizeBy": "sum"
          },
          {
            "name": "PoolQC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e771fb09-b426-420b-b99c-e20dadc99ff3",
            "sourceColumn": "PoolQC",
            "summarizeBy": "none"
          },
          {
            "name": "Fence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09e05f3a-1a45-4346-9ad0-5b362dd6fa4a",
            "sourceColumn": "Fence",
            "summarizeBy": "none"
          },
          {
            "name": "MiscFeature",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3c3ae84-5f93-4932-90ce-b3322899d10e",
            "sourceColumn": "MiscFeature",
            "summarizeBy": "none"
          },
          {
            "name": "MiscVal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5039993f-f86a-467b-88fc-d4c586eb730f",
            "sourceColumn": "MiscVal",
            "summarizeBy": "sum"
          },
          {
            "name": "MoSold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f4bb8e11-aaa7-4812-86eb-62c02dc9d506",
            "sourceColumn": "MoSold",
            "summarizeBy": "sum"
          },
          {
            "name": "YrSold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e1a3a5c-a371-4895-af70-71aa78f84da2",
            "sourceColumn": "YrSold",
            "summarizeBy": "sum"
          },
          {
            "name": "SaleType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0a55ef8-6c01-4d8d-ad19-ded8c3fb374c",
            "sourceColumn": "SaleType",
            "summarizeBy": "none"
          },
          {
            "name": "SaleCondition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc27cd81-de51-47cc-91f9-51d133c86cd1",
            "sourceColumn": "SaleCondition",
            "summarizeBy": "none"
          },
          {
            "name": "target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "924fc402-7069-4584-86ff-350a1a76801a",
            "sourceColumn": "target",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "93cc7f17-a0d1-4396-9b66-b0e503c8b4a2",
        "partitions": [
          {
            "name": "クエリ1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    ソース = SharePoint.Files(\"https://kcactived.sharepoint.com/sites/KC_Kumamoto/\", [ApiVersion = 15]),",
                "    並べ替えられた行 = Table.Sort(ソース,{{\"Date modified\", Order.Descending}}),",
                "    #\"ames_housing_dataset_train csv_https://kcactived sharepoint com/sites/KC_Kumamoto/Shared Documents/RD戦略チーム/PowerBI/\" = 並べ替えられた行{[Name=\"ames_housing_dataset_train.csv\",#\"Folder Path\"=\"https://kcactived.sharepoint.com/sites/KC_Kumamoto/Shared Documents/RD戦略チーム/PowerBI/\"]}[Content],",
                "    #\"インポートされた CSV\" = Csv.Document(#\"ames_housing_dataset_train csv_https://kcactived sharepoint com/sites/KC_Kumamoto/Shared Documents/RD戦略チーム/PowerBI/\",[Delimiter=\",\", Columns=81, Encoding=932, QuoteStyle=QuoteStyle.None]),",
                "    昇格されたヘッダー数 = Table.PromoteHeaders(#\"インポートされた CSV\", [PromoteAllScalars=true]),",
                "    変更された型 = Table.TransformColumnTypes(昇格されたヘッダー数,{{\"Id\", Int64.Type}, {\"MSSubClass\", Int64.Type}, {\"MSZoning\", type text}, {\"LotFrontage\", Int64.Type}, {\"LotArea\", Int64.Type}, {\"Street\", type text}, {\"Alley\", type text}, {\"LotShape\", type text}, {\"LandContour\", type text}, {\"Utilities\", type text}, {\"LotConfig\", type text}, {\"LandSlope\", type text}, {\"Neighborhood\", type text}, {\"Condition1\", type text}, {\"Condition2\", type text}, {\"BldgType\", type text}, {\"HouseStyle\", type text}, {\"OverallQual\", Int64.Type}, {\"OverallCond\", Int64.Type}, {\"YearBuilt\", Int64.Type}, {\"YearRemodAdd\", Int64.Type}, {\"RoofStyle\", type text}, {\"RoofMatl\", type text}, {\"Exterior1st\", type text}, {\"Exterior2nd\", type text}, {\"MasVnrType\", type text}, {\"MasVnrArea\", Int64.Type}, {\"ExterQual\", type text}, {\"ExterCond\", type text}, {\"Foundation\", type text}, {\"BsmtQual\", type text}, {\"BsmtCond\", type text}, {\"BsmtExposure\", type text}, {\"BsmtFinType1\", type text}, {\"BsmtFinSF1\", Int64.Type}, {\"BsmtFinType2\", type text}, {\"BsmtFinSF2\", Int64.Type}, {\"BsmtUnfSF\", Int64.Type}, {\"TotalBsmtSF\", Int64.Type}, {\"Heating\", type text}, {\"HeatingQC\", type text}, {\"CentralAir\", type text}, {\"Electrical\", type text}, {\"1stFlrSF\", Int64.Type}, {\"2ndFlrSF\", Int64.Type}, {\"LowQualFinSF\", Int64.Type}, {\"GrLivArea\", Int64.Type}, {\"BsmtFullBath\", Int64.Type}, {\"BsmtHalfBath\", Int64.Type}, {\"FullBath\", Int64.Type}, {\"HalfBath\", Int64.Type}, {\"BedroomAbvGr\", Int64.Type}, {\"KitchenAbvGr\", Int64.Type}, {\"KitchenQual\", type text}, {\"TotRmsAbvGrd\", Int64.Type}, {\"Functional\", type text}, {\"Fireplaces\", Int64.Type}, {\"FireplaceQu\", type text}, {\"GarageType\", type text}, {\"GarageYrBlt\", Int64.Type}, {\"GarageFinish\", type text}, {\"GarageCars\", Int64.Type}, {\"GarageArea\", Int64.Type}, {\"GarageQual\", type text}, {\"GarageCond\", type text}, {\"PavedDrive\", type text}, {\"WoodDeckSF\", Int64.Type}, {\"OpenPorchSF\", Int64.Type}, {\"EnclosedPorch\", Int64.Type}, {\"3SsnPorch\", Int64.Type}, {\"ScreenPorch\", Int64.Type}, {\"PoolArea\", Int64.Type}, {\"PoolQC\", type text}, {\"Fence\", type text}, {\"MiscFeature\", type text}, {\"MiscVal\", Int64.Type}, {\"MoSold\", Int64.Type}, {\"YrSold\", Int64.Type}, {\"SaleType\", type text}, {\"SaleCondition\", type text}, {\"target\", Int64.Type}})",
                "in",
                "    変更された型"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}